# Generated by Django 4.0.2 on 2022-03-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artist_post_special_alter_post_image_video_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
            preserve_default=False,
        ),
    ]
