# Generated by Django 4.0.2 on 2022-03-27 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_children_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.video'),
        ),
    ]
