# Generated by Django 4.0.2 on 2022-03-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_music_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
