# Generated by Django 4.0.2 on 2022-03-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_music_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(default='hello', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(default='Hello', on_delete=django.db.models.deletion.CASCADE, to='blog.artist'),
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.musiccategory'),
        ),
    ]
