# Generated by Django 4.0.2 on 2022-04-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_file_music_music_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='video',
            new_name='video_file',
        ),
    ]
