# Generated by Django 4.0.2 on 2022-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_video_music_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
