# Generated by Django 4.0.2 on 2022-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_music_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
