# Generated by Django 4.0.2 on 2022-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_musiccomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trending',
            field=models.BooleanField(default=True),
        ),
    ]
